kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-event-streams-kafka-0
  annotations:
    eventstreams.ibm.com/delete-claim: 'false'
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/part-of: eventstreams-event-streams
    app.kubernetes.io/instance: event-streams
    eventstreams.ibm.com/component-type: kafka
    eventstreams.ibm.com/name: event-streams-kafka
    eventstreams.ibm.com/kind: Kafka
    app.kubernetes.io/managed-by: eventstreams-cluster-operator
    app.kubernetes.io/name: kafka
    eventstreams.ibm.com/cluster: event-streams
    eventstreams.ibm.com/pool-name: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem