apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: event-streams
  labels:
    backup.eventstreams.ibm.com/component: eventstreams
  annotations:
    eventstreams.ibm.com/apicurio-registry-version: '>=2.4'
    argocd.argoproj.io/sync-wave: "100"
spec:
  license:
    accept: true
    license: L-VTPK-22YZPK
    use: CloudPakForIntegrationNonProduction
  strimziOverrides:
    kafka:
      config:
        inter.broker.protocol.version: '3.5'
        offsets.topic.replication.factor: 1
        transaction.state.log.min.isr: 1
        transaction.state.log.replication.factor: 1
      metricsConfig:
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: light-insecure-metrics-config
        type: jmxPrometheusExporter
      storage:
        type: persistent-claim
        class: ocs-storagecluster-ceph-rbd
        size: 100Gi
      listeners:
        - name: extscram
          type: route
          port: 9092
          tls: true
          authentication:
            type: scram-sha-512
        - name: exttls
          type: route
          port: 9093
          tls: true
          authentication:
            type: tls
      replicas: 1
    zookeeper:
      metricsConfig:
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: light-insecure-metrics-config
        type: jmxPrometheusExporter
      storage:
        type: persistent-claim
        class: ocs-storagecluster-ceph-rbd
        size: 100Gi
      replicas: 1
  adminUI:
    authentication:
      - type: scram-sha-512
  restProducer: {}
  apicurioRegistry: {}
  adminApi: {}
  collector: {}
  version: latest
