apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - data-event-streams-kafka.yaml
  - data-event-streams-zookeeper.yaml
  - instance.yaml
  - subscription.yaml

patches:
  - target:
      kind: EventStreams
      name: event-streams
    patch: |-
      - op: replace
        path: /spec/strimziOverrides/kafka/storage
        value: 'ocs-storagecluster-ceph-rbd'

replacements:
  - source:
      name: event-streams
      kind: EventStreams
      fieldPath: spec.strimziOverrides.kafka.storage
    targets:
      - select:
          kind: PersistentVolumeClaim
          name: data-event-streams-kafka-0
      - select:
          kind: PersistentVolumeClaim
          name: data-event-streams-zookeeper-0
        fieldPaths:
          - spec.storageClassName