apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-eventstreams
  namespace: openshift-operators
  labels:
    backup.eventstreams.ibm.com/component: subscription
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: v3.3
  name: ibm-eventstreams
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
